### ISSUE TITLE
optimize m2 repo for 7.4.28 and 8.0.5

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/m2-repo-carina#1]
subj

**Comment by vdelendik** [comment]
done, `public.ecr.aws/zebrunner/m2-repo-carina:1.1` built and published usinf 7.4.28 and 8.0.7 carina dependencies
https://github.com/zebrunner/m2-repo-carina/commit/49b1e3c675a31fc2cba0d582a9328b293116eba3

**Comment by ghost** [comment]
Execute web, api launchers  using branches: 8.0.7 and carina/7.4.28. Verify that execution logs doesn't contain downloading of 8.0.7 and 7.4.28 jars(only pom.xml). Also start from carina-demo master branch to see that downloading happens.

**Comment by ghost** [comment]
Verified on org.
execution logs contain downloading of 8.0.7 or 7.4.28 jars for web demo test with branches: 8.0.7 and carina/7.4.28

<img width="814" alt="Снимок экрана 2023-03-07 в 17 42 28" src="https://user-images.githubusercontent.com/32964663/223455863-9699184e-3203-4b0f-a0e7-2eedcf1476de.png">
<img width="804" alt="Снимок экрана 2023-03-07 в 17 29 43" src="https://user-images.githubusercontent.com/32964663/223455956-220b6b86-c3be-4bf1-b79b-c8e2c371a07c.png">
