### ISSUE TITLE
reuse default `main' branch for carina-demo 

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/m2-repo-carina#5]
during predownloading m2 dependencies let's switch to the default `main` branch

**Comment by vdelendik** [comment]
reused `main` branch to generate `m2-repo-carina:1.3-beta1` image which is deployed to dev esg

**Comment by ghost** [comment]
it looks, that this image is not present on dev env.
Execute web test with branch main and   m2-repo-carina:1.3-beta1 image
https://devtests.zebrunner.dev/projects/DEF/automation-launches/159401?runsState=cGFnZT0x&launchState=dGVzdHM%3D

**Comment by vdelendik** [comment]
it should be fixed now.

**Comment by ghost** [comment]
verified, fixed.
